# for gh-pages
baseurl = "https://dkebler.github.io/landingpage-guide/"
languageCode = "en-us"
title = "Landing Page User Guide"
canonifyUrls = "true"
staticDir ="assets"
publishDir = "docs"
contentDir = "sections"
layoutDir = "plugins"
theme = "landingpage-flex-hugo-theme"
# disqusShortname = "landingpage-guide"

[params]
custom_css = ["custom.css"]  # can add other files in array and make corresponding file in assets/css/
custom_js = ["custom.js","custom-docready.js"]  # can add other files in array and make corresponding file in assets/css/
galleries = ["photos"] # array of galleries names created
# imagespath = "https://mybuckettld/afolder/"  # full url must end with /
lightbox = "lightgallery" # must match the lightbox function name
# font = "Acme"  # a valid google font name, default Roboto, sets for entire site, can be specifically overridden

[params.navbar]
  #logo_text = "Will override site title"  # default is to use the site title
  logo_text_short = "Landing Page Guide" # helps to fit on small screens without wrapping
  # logo_text_size="1" # unit is em, 2em is default for small
  # font = "Ranga"
  #  For List of html colors see either
  # http://www.quackit.com/css/color/charts/css_color_names_chart.cfm
  # https://www.colorcodehex.com/html-color-names.html
  color = "ivory"
  bg_color = "coral"

[params.hero]
  # img = "../images/myhero.jpg"  # default is images/hero.jpg, must provide the full path or url
  # font = "Acme"  # a valid google font name, default Roboto for all hero text
  color = "darksalmon"
  # bg_color = "red"
  text_outline = "black"
  text_shadow = "black"
  # headlines_font = "Gloria Hallelujah"  # a valid google font name, defaults to intro font
  headline = "Landing Page Generator"
  headline_color = "firebrick"
  #headline_size = "4"
  subheadline = "Users Guide"
  # subheadline_color = "pink"
  # subheadline_size = "1"
  subsubheadline = "Hugo Powered!"
  subsubheadline_color = "brown"
  # subsubheadline_size = "1"
  lines = ["Customizable", "Add Your Sections", "Insert Your Content","Super Noob Friendly"]
  lines_color = "ivory"
  lines_size = ".65"
  divider = true
  # divider_color = "seagreen"
  # divider_thickness = "3"

[params.sections]
    #font = "Acme"
    bullet_icon = "\uF069"   # font awesome unicode value
    # headline_font = "Lato"
    # headline_size = "3"
    [params.sections.odd]
    bg_color = "bisque"
    color = "firebrick"
    [params.sections.even]
    color = "bisque"
    bg_color = "firebrick"
    [params.sections.footer]
    # color = "ivory"
    # bg_color = "darksalmon"
    [params.sections.comments]
    color = "black"
    bg_color = "ivory"

# these will overide the default which is even section button scheme comes from odd section scheme and vice versa
# default hover is simply
[params.buttons.even]
  # color = "blue"
  # bg_color = "red"
  # hover_color ="white"
  # hover_bg_color ="purple"
[params.buttons.odd]
  # color = "red"
  # bg_color = "blue"
  # hover_color ="purple"
  # hover_bg_color ="white"

# TODO enable via shortcode
[[params.social]]
    #title = "email"
    #icon = "envelope-o"
    #url = "mailto:4005@kebler.net"
